### ISSUE TITLE
1. 스타일 정하기

### ISSUE THREAD

**Issue by hoseong511** [calenderProjectJS/Calendar#1]
#### 1. 랜딩 페이지
  - 오늘의 일정 (일정 페이지 이동 가능)
  - 이번 주 요약 (해당 날짜 이동 가능)
  - 이번 달 캘린더 작게 (클릭 시 캘린더 페이지 이동 가능)

#### 2. 캘린더 화면
  - 한 달 기준
  - 헤더 버튼 : 이전 오늘 다음
  - 일정 여부, 기간 표시
  - 주말, 공휴일 표시

#### 3. 일정 Todo-list 화면
  - 헤더 전체선택버튼 | 텍스트인풋박스 | 추가버튼(+) | 필터

![Image](https://github.com/orgs/calenderProjectJS/projects/1/assets/157199245/a0a7546e-605f-4163-87fe-c45dc2992369)

![Image](https://github.com/orgs/calenderProjectJS/projects/1/assets/157199245/a2a9c46e-fcfe-4379-a9c0-690199b7d69b)

![Image](https://github.com/orgs/calenderProjectJS/projects/1/assets/157199245/f129abb3-ccab-469b-94d8-720c2c2eef57)

**Comment by dazzlingtea** [comment]
https://dribbble.com/shots/21075467-Daily-UI-71-Schedule

https://dribbble.com/shots/23211355-Calendate-s-Dashboard

**Comment by hoseong511** [comment]
멘션 기능도 됩니다. @dazzlingtea @asdkp12

**Comment by dazzlingtea** [comment]
랜딩 페이지 
저희 역할도 정해야할 것 같아요

![Image](https://github.com/calenderProjectJS/Calendar/assets/157199245/3e201026-8523-4915-8905-4de8b6146b3d)

**Comment by hoseong511** [comment]
#6 @dazzlingtea 
#5 @asdkp12 
#3 @hoseong511
