### ISSUE TITLE
2-4 메인 Weekly JS 구현

### ISSUE THREAD

**Issue by dazzlingtea** [calenderProjectJS/Calendar#24]
메인 대시보드 하단에 선택한 날짜에 따라 Weekly 바뀌도록 구현

**Comment by hoseong511** [comment]
나래님! 
https://github.com/calenderProjectJS/Calendar/blob/a8bd8df71a3c1880e5eedf5a61acf426e4f802c7/js/calendar.js#L121-L130
이 부분 querySelectAll 로 접근해서 모든 .date-container 의 addInactive, addTodayCircle 적용되게 바꿔주실 수 있을까요?
모달에 있는 달력 .date-container 태그에 calendar.js가 적용되었으면 합니다.
